name: CD/CI
run-name: Build Job ${{ github.event.head_commit.message }} by @${{ github.actor }}
env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
 VERSION: "v${{ github.head_ref || github.ref_name }}"
on:
  push:
    branches:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  workflow-pkgbuilder:
    uses: frefolli/action-pkgbuilder/workflow.yml@master
